name: Rust Build

on:
  push:
    branches: [ main, devel ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Install latest Rust nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: Compile
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

    - name: Rustfmt check
      run: cargo fmt -- --check

    - name: Clippy check
      run: cargo clippy